ALTER SESSION SET current_schema = HR; 

SELECT * FROM JOBS WHERE MIN_SALARY > 10000;

SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'YYYY') BETWEEN 2002 AND 2005 ORDER BY HIRE_DATE;

SELECT FIRST_NAME, HIRE_DATE
FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'SA_MAN');

SELECT * FROM EMPLOYEES  where hire_date > '01-jan-2008';


